const fs=require('fs');const d={categories:[
{id:"sports",name:"Riyada",nameAr:"رياضة",emoji:"⚽",pairs:[
{wordA:"كرة القدم",wordB:"كرة اليد",hint:"لعبة جماعية بكرة"},
{wordA:"سباحة",wordB:"غوص",hint:"في الماء"},
{wordA:"ملاكمة",wordB:"كراتيه",hint:"فنون قتالية"},
{wordA:"دراجة",wordB:"دراجة نارية",hint:"وسيلة تنقل"},
{wordA:"تنس",wordB:"تنس طاولة",hint:"مضرب وكرة"},
{wordA:"كرة سلة",wordB:"كرة طائرة",hint:"كرة وملعب"},
{wordA:"جري",wordB:"مشي",hint:"رياضة بالأرجل"},
{wordA:"رماية",wordB:"قوس",hint:"تصويب"},
{wordA:"جمباز",wordB:"يوغا",hint:"مرونة"},
{wordA:"تزلج",wordB:"تزلج على الماء",hint:"انزلاق"},
{wordA:"رفع أثقال",wordB:"كمال أجسام",hint:"عضلات"},
{wordA:"كريكت",wordB:"بيسبول",hint:"كرة ومضرب"},
{wordA:"هوكي",wordB:"هوكي جليد",hint:"عصا وكرة"},
{wordA:"مصارعة",wordB:"جودو",hint:"قتال"},
{wordA:"سكواش",wordB:"بادل",hint:"مضرب وجدار"},
{wordA:"ركبي",wordB:"كرة قدم أمريكية",hint:"كرة بيضاوية"},
{wordA:"فروسية",wordB:"بولو",hint:"خيل"},
{wordA:"تجديف",wordB:"كاياك",hint:"في الماء بمجداف"},
{wordA:"مبارزة",wordB:"سيف",hint:"سلاح أبيض"},
{wordA:"غولف",wordB:"بولينغ",hint:"كرة صغيرة"}
]},
{id:"food",name:"Mekla",nameAr:"ماكلة",emoji:"🍕",pairs:[
{wordA:"كسكس",wordB:"شخشوخة",hint:"أكلة تقليدية"},
{wordA:"شاورما",wordB:"برغر",hint:"أكل سريع"},
{wordA:"قهوة",wordB:"شاي",hint:"مشروب ساخن"},
{wordA:"بيتزا",wordB:"لازانيا",hint:"أكل إيطالي"},
{wordA:"تمر",wordB:"تين",hint:"فاكهة جافة"},
{wordA:"مشوي",wordB:"مقلي",hint:"طريقة طبخ"},
{wordA:"خبز",wordB:"بريوش",hint:"معجنات"},
{wordA:"حليب",wordB:"لبن",hint:"مشروب أبيض"},
{wordA:"دجاج",wordB:"ديك رومي",hint:"لحم أبيض"},
{wordA:"سوشي",wordB:"ساشيمي",hint:"أكل ياباني"},
{wordA:"فلافل",wordB:"حمص",hint:"أكل شامي"},
{wordA:"كريب",wordB:"بان كيك",hint:"فطائر رقيقة"},
{wordA:"شوكولاتة",wordB:"كراميل",hint:"حلوى"},
{wordA:"رز",wordB:"مكرونة",hint:"نشويات"},
{wordA:"زيتون",wordB:"زيت زيتون",hint:"من شجرة الزيتون"},
{wordA:"عسل",wordB:"مربى",hint:"حلو على الخبز"},
{wordA:"بطاطا مقلية",wordB:"ودجز",hint:"بطاطا"},
{wordA:"آيس كريم",wordB:"سوربيه",hint:"حلوى مجمدة"},
{wordA:"طاجين",wordB:"مرقة",hint:"طبخ في قدر"},
{wordA:"سمك",wordB:"جمبري",hint:"فواكه بحر"}
]},
{id:"animals",name:"Hayawanat",nameAr:"حيوانات",emoji:"🦁",pairs:[
{wordA:"أسد",wordB:"نمر",hint:"وحش كاسر"},
{wordA:"كلب",wordB:"قط",hint:"حيوان أليف"},
{wordA:"فيل",wordB:"زرافة",hint:"حيوان ضخم"},
{wordA:"دجاجة",wordB:"بطة",hint:"طيور مزرعة"},
{wordA:"دولفين",wordB:"حوت",hint:"حيوان بحري"},
{wordA:"عقرب",wordB:"ثعبان",hint:"حيوان خطير"},
{wordA:"نسر",wordB:"صقر",hint:"طائر جارح"},
{wordA:"غزال",wordB:"أيل",hint:"حيوان سريع"},
{wordA:"تمساح",wordB:"سحلية",hint:"زاحف"},
{wordA:"نحلة",wordB:"دبور",hint:"حشرة تلسع"},
{wordA:"حصان",wordB:"حمار",hint:"ركوب"},
{wordA:"باندا",wordB:"كوالا",hint:"حيوان لطيف"},
{wordA:"ذئب",wordB:"ثعلب",hint:"من فصيلة الكلاب"},
{wordA:"بومة",wordB:"خفاش",hint:"حيوان ليلي"},
{wordA:"سلحفاة",wordB:"حلزون",hint:"بطيء"},
{wordA:"قرد",wordB:"غوريلا",hint:"رئيسيات"},
{wordA:"فراشة",wordB:"يعسوب",hint:"حشرة طائرة"},
{wordA:"جمل",wordB:"لاما",hint:"حيوان صحراوي"},
{wordA:"ببغاء",wordB:"كناري",hint:"طائر ملون"},
{wordA:"أخطبوط",wordB:"حبار",hint:"حيوان بحري بأذرع"}
]},
{id:"cars",name:"Sayarat",nameAr:"سيارات",emoji:"🚗",pairs:[
{wordA:"بنزين",wordB:"ديزل",hint:"وقود"},
{wordA:"فيراري",wordB:"لامبورغيني",hint:"سيارة فاخرة"},
{wordA:"كهرباء",wordB:"هايبريد",hint:"محرك حديث"},
{wordA:"4×4",wordB:"جيب",hint:"سيارة طرق وعرة"},
{wordA:"برادو",wordB:"باترول",hint:"SUV مشهور"},
{wordA:"طيارة",wordB:"هليكوبتر",hint:"يطير"},
{wordA:"بي إم دبليو",wordB:"مرسيدس",hint:"سيارة ألمانية"},
{wordA:"تويوتا",wordB:"هوندا",hint:"سيارة يابانية"},
{wordA:"تسلا",wordB:"ريفيان",hint:"سيارة كهربائية"},
{wordA:"بورش",wordB:"أستون مارتن",hint:"سيارة رياضية"},
{wordA:"رينو",wordB:"بيجو",hint:"سيارة فرنسية"},
{wordA:"فولكسفاغن",wordB:"أودي",hint:"سيارة ألمانية شعبية"},
{wordA:"باص",wordB:"ترام",hint:"نقل جماعي"},
{wordA:"شاحنة",wordB:"بيك أب",hint:"نقل بضائع"},
{wordA:"دراجة نارية",wordB:"سكوتر",hint:"عجلتين بمحرك"},
{wordA:"سيارة إسعاف",wordB:"سيارة إطفاء",hint:"سيارة طوارئ"},
{wordA:"ليموزين",wordB:"رولز رويس",hint:"سيارة فخمة"},
{wordA:"فورد",wordB:"شيفروليه",hint:"سيارة أمريكية"},
{wordA:"كيا",wordB:"هيونداي",hint:"سيارة كورية"},
{wordA:"فيات",wordB:"ألفا روميو",hint:"سيارة إيطالية"}
]},
{id:"cities",name:"Mdun",nameAr:"مدن",emoji:"🏙️",pairs:[
{wordA:"الجزائر",wordB:"وهران",hint:"مدينة جزائرية"},
{wordA:"باريس",wordB:"لندن",hint:"عاصمة أوروبية"},
{wordA:"دبي",wordB:"أبوظبي",hint:"مدينة خليجية"},
{wordA:"القاهرة",wordB:"الإسكندرية",hint:"مدينة مصرية"},
{wordA:"تونس",wordB:"الرباط",hint:"عاصمة مغاربية"},
{wordA:"قسنطينة",wordB:"عنابة",hint:"شرق الجزائر"},
{wordA:"نيويورك",wordB:"لوس أنجلس",hint:"مدينة أمريكية"},
{wordA:"طوكيو",wordB:"سيول",hint:"مدينة آسيوية"},
{wordA:"روما",wordB:"مدريد",hint:"مدينة جنوب أوروبا"},
{wordA:"مكة",wordB:"المدينة",hint:"مدينة مقدسة"},
{wordA:"إسطنبول",wordB:"أنقرة",hint:"مدينة تركية"},
{wordA:"برلين",wordB:"ميونخ",hint:"مدينة ألمانية"},
{wordA:"بيروت",wordB:"دمشق",hint:"مدينة شامية"},
{wordA:"الدوحة",wordB:"الرياض",hint:"مدينة خليجية"},
{wordA:"مراكش",wordB:"فاس",hint:"مدينة مغربية"},
{wordA:"تلمسان",wordB:"بجاية",hint:"مدينة جزائرية"},
{wordA:"موسكو",wordB:"سان بطرسبرغ",hint:"مدينة روسية"},
{wordA:"سيدني",wordB:"ملبورن",hint:"مدينة أسترالية"},
{wordA:"بانكوك",wordB:"جاكرتا",hint:"مدينة جنوب شرق آسيا"},
{wordA:"تيزي وزو",wordB:"البليدة",hint:"ولاية جزائرية"}
]},
{id:"tech",name:"Tech",nameAr:"تكنولوجيا",emoji:"💻",pairs:[
{wordA:"آيفون",wordB:"سامسونج",hint:"هاتف ذكي"},
{wordA:"تيك توك",wordB:"إنستغرام",hint:"تطبيق اجتماعي"},
{wordA:"بلايستيشن",wordB:"إكسبوكس",hint:"جهاز ألعاب"},
{wordA:"يوتيوب",wordB:"نتفليكس",hint:"بث فيديو"},
{wordA:"واتساب",wordB:"تيليغرام",hint:"تطبيق رسائل"},
{wordA:"ويندوز",wordB:"ماك",hint:"نظام تشغيل"},
{wordA:"فيسبوك",wordB:"تويتر",hint:"شبكة اجتماعية"},
{wordA:"جوجل",wordB:"بينغ",hint:"محرك بحث"},
{wordA:"سبوتيفاي",wordB:"أبل ميوزك",hint:"بث موسيقى"},
{wordA:"زووم",wordB:"تيمز",hint:"مكالمات فيديو"},
{wordA:"لينكس",wordB:"أندرويد",hint:"نظام مفتوح"},
{wordA:"فوتوشوب",wordB:"كانفا",hint:"تصميم"},
{wordA:"بيتكوين",wordB:"إيثيريوم",hint:"عملة رقمية"},
{wordA:"أمازون",wordB:"علي بابا",hint:"تسوق إلكتروني"},
{wordA:"جيميل",wordB:"أوتلوك",hint:"بريد إلكتروني"},
{wordA:"نينتندو",wordB:"ستيم",hint:"منصة ألعاب"},
{wordA:"تشات جي بي تي",wordB:"جيميناي",hint:"ذكاء اصطناعي"},
{wordA:"دروبوكس",wordB:"غوغل درايف",hint:"تخزين سحابي"},
{wordA:"أوبر",wordB:"كريم",hint:"تطبيق توصيل"},
{wordA:"سناب شات",wordB:"بي ريل",hint:"قصص ومقاطع قصيرة"}
]},
{id:"status",name:"Statut",nameAr:"وضعيات",emoji:"😎",pairs:[
{wordA:"غني",wordB:"فقير",hint:"وضع مالي"},
{wordA:"متزوج",wordB:"عازب",hint:"حالة عائلية"},
{wordA:"طالب",wordB:"موظف",hint:"وضع مهني"},
{wordA:"رئيس",wordB:"مدير",hint:"رتبة في العمل"},
{wordA:"مشهور",wordB:"عادي",hint:"مكانة اجتماعية"},
{wordA:"متقاعد",wordB:"نشيط",hint:"وضع مهني"},
{wordA:"سعيد",wordB:"حزين",hint:"حالة نفسية"},
{wordA:"متفائل",wordB:"متشائم",hint:"نظرة للحياة"},
{wordA:"كسول",wordB:"نشيط",hint:"طاقة"},
{wordA:"خجول",wordB:"جريء",hint:"شخصية"},
{wordA:"صبور",wordB:"عصبي",hint:"مزاج"},
{wordA:"كريم",wordB:"بخيل",hint:"صفة مالية"},
{wordA:"ذكي",wordB:"ماكر",hint:"عقل"},
{wordA:"طويل",wordB:"قصير",hint:"قامة"},
{wordA:"نحيف",wordB:"سمين",hint:"بنية جسم"},
{wordA:"منظم",wordB:"فوضوي",hint:"ترتيب"},
{wordA:"صامت",wordB:"ثرثار",hint:"كلام"},
{wordA:"شجاع",wordB:"جبان",hint:"شجاعة"},
{wordA:"محظوظ",wordB:"منحوس",hint:"حظ"},
{wordA:"رومانسي",wordB:"عملي",hint:"طريقة تفكير"}
]},
{id:"movies",name:"Aflam",nameAr:"أفلام",emoji:"🎬",pairs:[
{wordA:"أكشن",wordB:"مغامرة",hint:"نوع فيلم"},
{wordA:"رعب",wordB:"إثارة",hint:"فيلم مخيف"},
{wordA:"كوميديا",wordB:"ستاند أب",hint:"مضحك"},
{wordA:"مارفل",wordB:"دي سي",hint:"أبطال خارقين"},
{wordA:"ممثل",wordB:"مخرج",hint:"صناعة سينما"},
{wordA:"أوسكار",wordB:"غولدن غلوب",hint:"جائزة سينمائية"},
{wordA:"بوب كورن",wordB:"ناتشوز",hint:"أكل سينما"},
{wordA:"مسلسل",wordB:"فيلم وثائقي",hint:"محتوى مرئي"},
{wordA:"أنيمي",wordB:"كارتون",hint:"رسوم متحركة"},
{wordA:"سوبرمان",wordB:"باتمان",hint:"بطل خارق"},
{wordA:"هاري بوتر",wordB:"سيد الخواتم",hint:"فيلم فانتازيا"},
{wordA:"ديزني",wordB:"بيكسار",hint:"استوديو رسوم"},
{wordA:"تيتانيك",wordB:"أفاتار",hint:"فيلم كاميرون"},
{wordA:"نتفليكس",wordB:"ديزني بلس",hint:"منصة بث"},
{wordA:"جيمس بوند",wordB:"جون ويك",hint:"بطل أكشن"},
{wordA:"سبايدرمان",wordB:"آيرون مان",hint:"بطل مارفل"},
{wordA:"كوميكس",wordB:"مانغا",hint:"قصص مصورة"},
{wordA:"3D",wordB:"IMAX",hint:"تقنية سينما"},
{wordA:"دراما",wordB:"ميلودراما",hint:"نوع مؤثر"},
{wordA:"زومبي",wordB:"مصاص دماء",hint:"وحش في الأفلام"}
]},
{id:"music",name:"Musica",nameAr:"موسيقى",emoji:"🎵",pairs:[
{wordA:"راب",wordB:"تراب",hint:"نوع موسيقى حديثة"},
{wordA:"راي",wordB:"شعبي",hint:"موسيقى جزائرية"},
{wordA:"بيانو",wordB:"غيتار",hint:"آلة موسيقية"},
{wordA:"طبل",wordB:"دربوكة",hint:"آلة إيقاعية"},
{wordA:"ميكروفون",wordB:"سماعات",hint:"أداة صوت"},
{wordA:"حفلة",wordB:"مهرجان",hint:"حدث موسيقي"},
{wordA:"بوب",wordB:"روك",hint:"نوع موسيقى غربية"},
{wordA:"كمان",wordB:"تشيلو",hint:"آلة وترية"},
{wordA:"دي جي",wordB:"منتج",hint:"صانع موسيقى"},
{wordA:"أغنية",wordB:"موال",hint:"لحن بكلمات"},
{wordA:"جاز",wordB:"بلوز",hint:"موسيقى أمريكية"},
{wordA:"فلوت",wordB:"ساكسوفون",hint:"آلة نفخ"},
{wordA:"كورال",wordB:"سولو",hint:"أداء غنائي"},
{wordA:"ريمكس",wordB:"كوفر",hint:"نسخة من أغنية"},
{wordA:"ألبوم",wordB:"سينغل",hint:"إصدار موسيقي"},
{wordA:"كليب",wordB:"بودكاست",hint:"محتوى صوتي/مرئي"},
{wordA:"عود",wordB:"قانون",hint:"آلة شرقية"},
{wordA:"هيب هوب",wordB:"آر أند بي",hint:"موسيقى أمريكية"},
{wordA:"أوبرا",wordB:"باليه",hint:"فن كلاسيكي"},
{wordA:"قناوة",wordB:"أندلسي",hint:"موسيقى مغاربية تقليدية"}
]},
{id:"school",name:"Madrasa",nameAr:"مدرسة",emoji:"📚",pairs:[
{wordA:"رياضيات",wordB:"فيزياء",hint:"مادة علمية"},
{wordA:"أستاذ",wordB:"مدير",hint:"شخص في المدرسة"},
{wordA:"امتحان",wordB:"فرض",hint:"اختبار"},
{wordA:"دفتر",wordB:"كتاب",hint:"أداة دراسة"},
{wordA:"قلم",wordB:"ممحاة",hint:"أداة كتابة"},
{wordA:"ساحة",wordB:"ملعب",hint:"مكان في المدرسة"},
{wordA:"حقيبة",wordB:"مقلمة",hint:"أغراض مدرسية"},
{wordA:"جغرافيا",wordB:"تاريخ",hint:"مادة اجتماعيات"},
{wordA:"عربية",wordB:"فرنسية",hint:"مادة لغة"},
{wordA:"باك",wordB:"بريفي",hint:"شهادة"},
{wordA:"سبورة",wordB:"طباشير",hint:"أداة شرح"},
{wordA:"غياب",wordB:"تأخر",hint:"مشكلة تلميذ"},
{wordA:"علوم",wordB:"أحياء",hint:"مادة طبيعية"},
{wordA:"واجب",wordB:"بحث",hint:"عمل منزلي"},
{wordA:"معدل",wordB:"نقطة",hint:"تقييم"},
{wordA:"إنجليزية",wordB:"إسبانية",hint:"لغة أجنبية"},
{wordA:"رياضة",wordB:"موسيقى",hint:"مادة ترفيهية"},
{wordA:"مختبر",wordB:"مكتبة",hint:"غرفة في المدرسة"},
{wordA:"تلميذ",wordB:"طالب جامعي",hint:"متعلم"},
{wordA:"نجاح",wordB:"رسوب",hint:"نتيجة"}
]},
{id:"places",name:"Amaken",nameAr:"أماكن",emoji:"🏖️",pairs:[
{wordA:"مسجد",wordB:"كنيسة",hint:"مكان عبادة"},
{wordA:"مطعم",wordB:"مقهى",hint:"مكان أكل وشرب"},
{wordA:"مستشفى",wordB:"عيادة",hint:"مكان علاج"},
{wordA:"مطار",wordB:"ميناء",hint:"مكان سفر"},
{wordA:"شاطئ",wordB:"مسبح",hint:"مكان سباحة"},
{wordA:"جبل",wordB:"غابة",hint:"طبيعة"},
{wordA:"سوق",wordB:"مول",hint:"مكان تسوق"},
{wordA:"ملعب",wordB:"صالة رياضية",hint:"مكان رياضة"},
{wordA:"سينما",wordB:"مسرح",hint:"مكان ترفيه"},
{wordA:"بنك",wordB:"بريد",hint:"مكان معاملات"},
{wordA:"فندق",wordB:"نزل",hint:"مكان إقامة"},
{wordA:"حديقة",wordB:"منتزه",hint:"مكان أخضر"},
{wordA:"مدرسة",wordB:"جامعة",hint:"مكان تعليم"},
{wordA:"صيدلية",wordB:"مخبر تحاليل",hint:"مكان صحة"},
{wordA:"محطة قطار",wordB:"محطة باص",hint:"مكان نقل"},
{wordA:"صحراء",wordB:"واحة",hint:"مكان جاف"},
{wordA:"سجن",wordB:"محكمة",hint:"مكان عدالة"},
{wordA:"متحف",wordB:"معرض",hint:"مكان ثقافة"},
{wordA:"مخبزة",wordB:"حلويات",hint:"مكان يبيع أكل"},
{wordA:"حمام تركي",wordB:"سبا",hint:"مكان استرخاء"}
]},
{id:"clothes",name:"Hwaij",nameAr:"لباس",emoji:"👕",pairs:[
{wordA:"قميص",wordB:"تيشيرت",hint:"لباس علوي"},
{wordA:"جينز",wordB:"بنطلون كلاسيك",hint:"لباس سفلي"},
{wordA:"حذاء رياضي",wordB:"صندل",hint:"حذاء"},
{wordA:"قبعة",wordB:"طاقية",hint:"غطاء رأس"},
{wordA:"نظارات شمس",wordB:"نظارات طبية",hint:"نظارات"},
{wordA:"ساعة",wordB:"سوار",hint:"إكسسوار يد"},
{wordA:"جاكيت",wordB:"معطف",hint:"لباس شتوي"},
{wordA:"شورت",wordB:"برمودا",hint:"لباس قصير"},
{wordA:"ربطة عنق",wordB:"بابيون",hint:"إكسسوار رقبة"},
{wordA:"عباية",wordB:"جلابة",hint:"لباس تقليدي"},
{wordA:"بيجاما",wordB:"روب",hint:"لباس بيت"},
{wordA:"حزام",wordB:"حمالات",hint:"يمسك البنطلون"},
{wordA:"جوارب",wordB:"جوارب طويلة",hint:"لباس قدم"},
{wordA:"فستان",wordB:"تنورة",hint:"لباس نسائي"},
{wordA:"كوستيم",wordB:"سموكينغ",hint:"لباس رسمي"},
{wordA:"قندورة",wordB:"برنوس",hint:"لباس جزائري تقليدي"},
{wordA:"خاتم",wordB:"سلسلة",hint:"مجوهرات"},
{wordA:"وشاح",wordB:"حجاب",hint:"غطاء"},
{wordA:"نايك",wordB:"أديداس",hint:"ماركة رياضية"},
{wordA:"زارا",wordB:"إتش أند إم",hint:"ماركة ملابس"}
]}
]};
fs.writeFileSync('./src/GameData.json',JSON.stringify(d,null,2),'utf8');
console.log('Done! Categories:',d.categories.length,'Total pairs:',d.categories.reduce((s,c)=>s+c.pairs.length,0));
